#!/bin/bash

# get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(/bin/cat /proc/loadavg | awk '{ print $1,$2,$3 }')
# get free memory
IFS=" " read USED FREE TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$4,$2'})
# get processes
PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`

W="\e[0;39m"
G="\e[1;32m"

#tempfile_c="/var/log/apt/apt-updates_count.log"
#count=$(cat $tempfile_c | wc -l)

echo -e "
$W  Distro......: $W`cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g'` - Updates availible: $W$count$G 
$W  Kernel......: $W`uname -sr`
$W  Uptime......: $W`uptime -p`
$W  CPU.........: $W`cat /proc/cpuinfo | grep "model name" | cut -d ' ' -f3- | awk {'print $0'} | head -1`
$W  Load........: $G$LOAD1$W (1m), $G$LOAD5$W (5m), $G$LOAD15$W (15m)
$W  Memory......: $G$USED$W used, $G$FREE$W free, $G$TOTAL$W in total$W"


printf "\nIP addresses:"
#printf "IP.Address=\"%s\" \n" $(hostname --all-ip-addresses) | grep -v 127.0.0 | grep -v '127.0.0.1' | grep -v '172.27'
_eth0=$(ip route show | grep 'br0 proto' | head -2 | tail -1)
_zt=$(ip route show | grep zt | head -2 | tail -1)
echo -e "\t $G$_eth0$W"
echo -e "\t\t $G$_zt$W"

services=( "grafana-server" "influxdb" "telegraf" "mysql" "mongod" "docker" "rsyslog" "apache2" "nginx" "plesk-php73-fpm.service" "memcached" "mariadb.service" "fail2ban" "openvpn@knaak_wasserstadt.service" "openvpnas" "spamassassin" "zerotier-one.service" "zabbix-agent" )
# sort services
IFS=$'\n' services=($(sort <<<"${services[*]}"))
