#!/bin/bash

# set column width
COLUMNS=6
# colors
green="\e[1;32m"
red="\e[1;31m"
undim="\e[0m"
services=( "grafana-server" "influxdb" "telegraf" "mysql" "mongod" "docker" "rsyslog" "apache2" "nginx" "plesk-php73-fpm.service" "memcached" "mariadb.service" "fail2ban" "openvpn@knaak_wasserstadt.service" "openvpnas" "spamassassin" "zerotier-one.service" "zabbix-agent" )
# sort services
IFS=$'\n' services=($(sort <<<"${services[*]}"))
unset IFS

service_status=()
# get status of all services
for service in "${services[@]}"; do
    service_status+=($(systemctl is-active "$service"))
done

for i in ${!services[@]}; do
    # color green if service is active, else red
    if [[ "${service_status[$i]}" == "active" ]]; then
        out+="${green}${services[$i]}${undim},"
    else
        out+="${red}${services[$i]}${undim},"
    fi
    # insert \n every $COLUMNS column
    if [ $((($i+1) % $COLUMNS)) -eq 0 ]; then
        out+="\n"
    fi
done
out+="\n"

printf "\nservices:\n"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
