#!/bin/bash
sudo grafana-cli plugins install agenty-flowcharting-panel
sudo grafana-cli plugins install alexanderzobnin-zabbix-app
sudo grafana-cli plugins install alexandra-trackmap-panel
sudo grafana-cli plugins install andig-darksky-datasource
sudo grafana-cli plugins install blackmirror1-singlestat-math-panel
sudo grafana-cli plugins install blackmirror1-statusbygroup-panel
sudo grafana-cli plugins install briangann-datatable-panel
sudo grafana-cli plugins install btplc-alarm-box-panel 
sudo grafana-cli plugins install btplc-peak-report-panel 
sudo grafana-cli plugins install btplc-trend-box-panel
sudo grafana-cli plugins install citilogics-geoloop-panel 
sudo grafana-cli plugins install corpglory-progresslist-panel 
sudo grafana-cli plugins install digiapulssi-breadcrumb-panel 
sudo grafana-cli plugins install digrich-bubblechart-panel 
sudo grafana-cli plugins install farski-blendstat-panel 
sudo grafana-cli plugins install fetzerch-sunandmoon-datasource 
sudo grafana-cli plugins install fzakaria-simple-annotations-datasource
sudo grafana-cli plugins install grafana-clock-panel
sudo grafana-cli plugins install grafana-image-renderer 
sudo grafana-cli plugins install grafana-imageviewer
sudo grafana-cli plugins install grafana-piechart-panel 
sudo grafana-cli plugins install grafana-polystat-panel 
sudo grafana-cli plugins install grafana-simple-json-backend-datasource 
sudo grafana-cli plugins install grafana-simple-json-datasource
sudo grafana-cli plugins install grafana-worldmap-panel-ng 
sudo grafana-cli plugins install jdbranham-diagram-panel 
sudo grafana-cli plugins install larona-epict-panel
sudo grafana-cli plugins install linksmart-hds-datasource 
sudo grafana-cli plugins install marcuscalidus-svg-panel 
sudo grafana-cli plugins install michaeldmoore-annunciator-panel 
sudo grafana-cli plugins install michaeldmoore-multistat-panel 
sudo grafana-cli plugins install grafana-mongodb-datasource 
sudo grafana-cli plugins install monitoringartist-monitoringart-datasource 
sudo grafana-cli plugins install mtanda-google-calendar-datasource 
sudo grafana-cli plugins install mtanda-heatmap-epoch-panel 
sudo grafana-cli plugins install mtanda-histogram-panel 
sudo grafana-cli plugins install mxswat-separator-panel 
sudo grafana-cli plugins install natel-discrete-panel 
sudo grafana-cli plugins install natel-influx-admin-panel 
sudo grafana-cli plugins install natel-plotly-panel 
sudo grafana-cli plugins install neocat-cal-heatmap-panel 
sudo grafana-cli plugins install novalabs-annotations-panel 
sudo grafana-cli plugins install petrslavotinek-carpetplot-panel 
sudo grafana-cli plugins install pierosavi-imageit-panel 
sudo grafana-cli plugins install pr0ps-trackmap-panel 
sudo grafana-cli plugins install raintank-worldping-app 
sudo grafana-cli plugins install ryantxu-ajax-panel 
sudo grafana-cli plugins install ryantxu-annolist-panel 
sudo grafana-cli plugins install savantly-heatmap-panel 
sudo grafana-cli plugins install simpod-json-datasource 
sudo grafana-cli plugins install smartmakers-trafficlight-panel 
sudo grafana-cli plugins install snuids-trafficlights-panel 
sudo grafana-cli plugins install vonage-status-panel 
sudo grafana-cli plugins install yesoreyeram-boomtable-panel 
sudo grafana-cli plugins install zuburqan-parity-report-panel 
sudo service grafana-server restart